<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
<head>
	<title><?=$message ?></title>

	<base href="<?=cAppUrl ?>/" >
	<meta content="text/html; charset=<?=cmfCharset ?>" http-equiv="Content-Type">
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<link href="<?=cAdminUrl ?>/styles.css" rel="stylesheet" type="text/css" />

</head>
<body>
<br><br>
<p><?=$message ?></p>
</body>
</html>