<?=$list->html()->startForm('filter') ?>
	<table class="table_position">
	<tr class="header_col">
	<td width="25%">Тип: <?=cmfView::selectOncahge($filterType) ?></td>
	<td width="25%">Начало: <input name="start" type="text" value="<?=cString::specialchars($list->getFilter('start')) ?>" onfocus="cmf.pages.focus(this);"></td>
	<td width="25%">Конец: <input name="end" type="text" value="<?=cString::specialchars($list->getFilter('end')) ?>" onfocus="cmf.pages.focus(this);"></td>
	<td width="25%"><?=cmfAdminView::onclickType1("filter.postAjax('changeFilter');", 'Применить') ?></td>
	</tr>
	</table>
<script type="text/javascript">
cmf.pages.input = false;
cmf.pages.cal = Calendar.setup({

    onSelect: function(cal) {
        cmf.pages.updateFields(cal);
        cal.hide()
    },
    onTimeChange: function(cal) {
        cmf.pages.updateFields(cal);
    },
});
cmf.pages.focus = function(input) {
    cmf.pages.input = input;
    var date = (new RegExp("([0-9]{2})\.([0-9]{2})\.([0-9]{4})")).exec(input.value);
    cmf.pages.cal.setHours(date[4]);
    cmf.pages.cal.setMinutes(date[5]);
    date = new Date(date[3], date[2]-1, date[1]);
    cmf.pages.cal.selection.set(date)
    cmf.pages.cal.moveTo(date)
    cmf.pages.cal.popup(input, 'right');
}
cmf.pages.updateFields = function(cal) {
    var date = cal.selection.get();
    if (date) {
        date = Calendar.intToDate(date);
		date.setHours(cal.getHours());
		date.setMinutes(cal.getMinutes());
		cmf.pages.input.value = Calendar.printDate(date, "%d-%m-%Y");
	}
};
</script>
<?=$list->html()->endForm() ?>



<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td>№</td>
	<td>Дата</td>
	<td>Статус</td>
	<td>Email</td>
	<td>Сумма</td>
	<td>Сумма скидки</td>
	<td>Сумма доставки</td>
	<td>Общая сумма</td>
	</tr>

	<?=view_list::startTR($list) ?>
	<td colspan="7"></td>
	</tr>

<?	$sum1 = $sum2 = $sum3 = $sum4 = 0;
    $status = cmfOrder::getStatusList(1, 2);
    foreach($list as $key=>$value) if($key) {
		list($form, $data) = $value->main;
		list(, $email, $userData, $userAdress, $userSubscribe) = unserialize($data->data);
		list($countAll, $priceAll, $priceDiscount, $priceDelivery, $discount) = unserialize($data->price);
        $delivery = $data->deliveryPrice;

        if(isset($status[$data->status])) {
            $sum1 += $list->filterPrice($priceAll);
    		$sum2 += $list->filterPrice($discount);
    		$sum3 += $list->filterPrice($delivery);
    		$sum4 += $list->filterPrice($priceDelivery);
        }
		?>

	<?=view_list::startTR($list) ?>
	<td><?=$key ?></td>
	<td><?=$data->orderDate ?></td>
	<td><?=$list->getStatus($data->status) ?></td>

	<td><?=$email ?></td>
	<td><?=$priceAll ?></td>
	<td><?=$discount ?></td>
	<td><?=$delivery ?></td>
	<td><?=$priceDelivery ?></td>
	</tr>
<? } ?>

	<tr class="header_col">
	<td>Итого:</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td>&nbsp;</td>
	<td><?=cmfPrice::view2($sum1) ?></td>
	<td><?=cmfPrice::view2($sum2) ?></td>
	<td><?=cmfPrice::view2($sum3) ?></td>
	<td><?=cmfPrice::view2($sum4) ?></td>
	</tr>
	</table>
<?=$list->html()->endForm() ?>
