	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjaxSave('update');", 'Сохранить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить') .
	                   cmfAdminView::buttonType2($edit->url()->getCatalog(), 'Вернуться')) ?>


<?=$edit->html()->startForm() ?>
<? list($form) = $edit->current()->main ?>
<table class="great_table">
<tr class="header_col">
<td colspan="2">&nbsp;</td>
</tr>

<tr>
<td class="svet_td">Название:</td>
<td class="svet_td2"><?=$form->html('name', 'class="width99"') ?></td>
</tr>

<tr>
<td class="svet_td">Отображать:</td>
<td class="svet_td2"><?=$form->html('visible') ?></td>
</tr>

</table>
<?=$edit->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjaxSave('update');", 'Сохранить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить') .
	                   cmfAdminView::buttonType2($edit->url()->getCatalog(), 'Вернуться')) ?>