<table class="great_table sectionCommand">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionCommand').hide(); $('.sectionEdit').show(); ">Показать настройки</a></td>
</tr>
</table>

<?=$config->html()->startForm('edit') ?>
<? list($configForm) = $config->current()->main ?>
<table class="great_table sectionEdit cHide"">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionEdit').hide(); $('.sectionCommand').show(); ">Скрыть настройки</a></td>
</tr>
<tr>
<td colspan="2" class="svet_td">
    <? view_command::viewLineButton(
                       cmfAdminView::buttonType1("edit.postAjax('update');", 'Сохранить')) ?>
</td>
</tr>
<tr>
<td class="svet_td">Информация на странице заказа:</td>
<td class="svet_td2"><?=$configForm->html('basket', 'class="width99" rows="7"') ?></td>
</tr>
</table>
<?=$config->html()->endForm() ?>


	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td>Название</td>
	<td width="50px">Стоимость</td>
	<td width="100px">Указывать <br />город и индекс</td>
	<td width="100px">Указывать <br />адрес</td>
	<td width="22px">Вид</td>
	<td width="22px">Удалить</td>
	</tr>

<?	foreach($list as $key=>$value){
		list($form, $data) = $value->main;
	 ?>
	<?=view_list::startTR($list) ?>
	<?=$list->getPostMove($data) ?>
	<td>
	    <?=$form->html('name', 'class="width99"') ?>
	    <?=$form->html('notice', 'class="width99"') ?>
	    <br /><br />Пояснение к заказу
	    <?=$form->html('basket', 'class="width99"') ?>
	</td>
	<td><?=$form->html('price') ?></td>
	<td><?=$form->html('isContact') ?></td>
	<td><?=$form->html('isDelivery') ?></td>
	<td><?=$form->html('visible') ?></td>
	<td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
