<?=$list->html()->startForm('filter') ?>
	<table class="table_position">

    <tr class="header_col">
    <td width="33%">Разделы: <?=cmfView::selectOncahge($filterSection, 'class="width99"') ?></td>
    <td width="33%" colspan="2">Производитель: <?=cmfView::selectOncahge($filterBrand, 'class="width99"') ?></td>
	<td width="33%">Фильтр: <?=cmfView::selectOncahge($filterFilter, 'class="width99"') ?></td>
	</tr>

	<tr class="header_col">
	<td colspan="2">
    	Артикул <input name="articul" id="articul" type="text" value="<?=$articul ?>" size="30">
    	<br /><?=cmfAdminView::onclickType1("filter.postAjax('changeFilter');", 'Найти') ?>&nbsp;&nbsp;
    	<?=cmfAdminView::onclickType1("cmf.setValue('articul', ''); filter.postAjax('changeFilter');", 'Сброс') ?>
	</td>
	<td colspan="2">
    	Цена: от <input name="price1" id="price1" type="text" value="<?=$price1 ?>" size="10">
    	до <input name="price2" id="price2" type="text" value="<?=$price2 ?>" size="10">&nbsp;&nbsp;
    	<br /><?=cmfAdminView::onclickType1("filter.postAjax('changeFilter');", 'Найти') ?>&nbsp;&nbsp;
    	<?=cmfAdminView::onclickType1("cmf.setValue('price1', ''); cmf.setValue('price2', ''); filter.postAjax('changeFilter');", 'Сброс') ?>
	</td>
	</tr>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLimitButton(
						'<td width="120px">Всего товаров: <b>'. $list->getTotal() .'</b></td>',
						$limitUrl, $linkPage, '') ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="10px">#</td>
	<td width="50px">Артикул</td>
	<td>Название</td>
	<td width="80px">Цена</td>
	<td width="50%" colspan="2">Остатки</td>
	</tr>

<? foreach($list as $key=>$value){
		list($form, $data) = $value->main;
		if($data->is('paramDump')) {
            $dump = cString::unserialize($data->paramDump);
            $param = cString::unserialize($data->param);
            list($basket, $value) = $list->getBasketId($data->section);
    		$param = get($param, $basket);
		} else {
		    $dump = $param = array();
		}
		?>
	<?=view_list::startTR($list) ?>

	<td><?=$data->pos ?></td>
	<td><?=$data->articul ?></td>
	<td><?=$data->name ?></td>

	<td><?=$data->price ?> руб.</td>
	<td><?=$data->count ?></td>
	<td width="45%">
    	<? foreach($param as $k=>$v) if(isset($value[$k])) { ?>
            <div class="selectDump"><?=get($value, $k) ?>: <?=get($dump, $k, 0) ?></div>
    	<? } ?>
	</td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLimitButton(
						'<td width="120px">Всего товаров: <b>'. $list->getTotal() .'</b></td>',
						$limitUrl, $linkPage, '') ?>

