
<table class="great_table">
<tr class="header_col">
<td colspan="2">Информация по рассылке</td>
</tr>

<tr>
<td class="svet_td">Дата:</td>
<td class="svet_td2"><?=$data->date ?>
</td>
</tr>

<tr>
<td class="svet_td">Список почты:</td>
<td class="svet_td2"><?=$data->email ?></td>
</tr>

<tr>
<td class="svet_td">Заголовок:</td>
<td class="svet_td2"><?=$data->header ?></td>
</tr>

<tr>
<td class="svet_td">Контент:</td>
<td class="svet_td2"><?=$data->content ?></td>
</tr>

</table>