                <div class="footer-menu">
                    <ul>
                    <? foreach($_menu as $row) { ?>
                        <li class="sep"></li>
                        <li><a href="<?=$row['url'] ?>"><?=$row['name'] ?></a></li>
                    <? } ?>
                        <li class="sep"></li>
                    </ul>
                </div>
                <div class="news-block">
                    <? foreach($_news as $row) { ?>
                    <div class="news-item">
                        <h3><a href="<?=$row['url'] ?>"><?=$row['header'] ?></a></h3>
                        <p><?=$row['notice'] ?></p>
                        <p class="news-item-date"><?=$row['date'] ?></p>
                    </div>
                    <? } ?>
                </div>
                <div class="footer-contacts">
                    <div class="subscribe">
                        <?=$subscribeYes->startForm() ?>
                            <fieldset>
                                <input type="submit" class="subscribe-btn" value="" />
                                <?=$form->html('email', ' class="subscribe-text" title="Ваш email"') ?>
                                <label>Подпишитесь на новости: </label>
                            </fieldset>
                        <?=$subscribeYes->endForm() ?>
                    </div>
                    <div class="email"><a href="mailto:<?=$email ?>"><?=$email ?></a></div>
                    <div class="social">
                        <span>Следуйте за нами:</span>
                        <?=$network ?>
                    </div>
                </div>
                <div class="catalog">
                    <div id="tabs">
                        <ul class="tabs-head">
                            <li class="active"><span><a>Популярные</a></span></li>
                            <li><span><a>Новинки</a></span></li>
                        </ul>
                        <div class="tabs-content">
                            <div id="tabs-1" class="tab">
                                <ul class="catalog-items">
                                <? foreach($_product['view'] as $id=>$row) { ?>
                                    <li>
                                        <? if(!$row['isDiscount']) { ?>
                                            <div class="b-sale-icon"><img src="<?=$row['discount'] ?>"></div>
                                        <? } ?>
                                        <div class="catalog-item-img">
                                            <a href="<?=$row['url'] ?>" class="jTip" id="<?=$id ?>view"><img src="<?=$row['image'] ?>" alt="<?=$row['title'] ?>" width="215" height="280" /></a>
                                        </div>
                                        <h4><a href="<?=$row['url'] ?>"><?=$row['name'] ?></a></h4>
                                        <p><?=$row['bName'] ?></p>
                                        <div class="catalog-item-price">
                                            <a href="<?=$row['url'] ?>"><span><?=$row['isOrder'] ? 'заказать' : 'купить' ?></span></a>
                                            <span>
                                                <? if(!$row['isDiscount']) { ?><del><?=cmfPrice::view2($row['priceOld']) ?></del><? } ?>
                                                <?=cmfPrice::view($row) ?> <img src="images/R.png" alt="R" width="11" height="12" />
                                            </span>
                                        </div>
                                    </li>
                                <? } ?>
                                </ul>
                            </div>
                            <div id="tabs-2" class="tab cHide">
                                <ul class="catalog-items">
                                <? foreach($_product['new'] as $id=>$row) { ?>
                                    <li>
                                        <? if(!$row['isDiscount']) { ?>
                                            <div class="b-sale-icon"><img src="<?=$row['discount'] ?>"></div>
                                        <? } ?>
                                        <div class="catalog-item-img">
                                            <a href="<?=$row['url'] ?>" class="jTip" id="<?=$id ?>new"><img src="<?=$row['image'] ?>" alt="<?=$row['title'] ?>" width="215" height="280" /></a>
                                        </div>
                                        <h4><a href="<?=$row['url'] ?>"><?=$row['name'] ?></a></h4>
                                        <p><?=$row['bName'] ?></p>
                                        <div class="catalog-item-price">
                                            <a href="<?=$row['url'] ?>"><span><?=$row['isOrder'] ? 'заказать' : 'купить' ?></span></a>
                                            <span>
                                                <? if(!$row['isDiscount']) { ?><del><?=cmfPrice::view2($row['priceOld']) ?></del><? } ?>
                                                <?=cmfPrice::view($row) ?> <img src="images/R.png" alt="R" width="11" height="12" />
                                            </span>
                                        </div>
                                    </li>
                                <? } ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <? if(isset($_article)) { ?>
                    <div class="article-block-header">
                        <div class="title">Статьи</div>
                        <div class="more"><a href="<?=$articleUrl ?>">все статьи »</a></div>
                    </div>
                    <div class="clearFloat"></div>
                    <div class="article-block">
                        <? foreach($_article as $row) { ?>
                        <div class="news-item">
                            <h3><a href="<?=$row['url'] ?>"><?=$row['header'] ?></a></h3>
                            <? if($row['image']) { ?>
                                <a href="<?=$row['url'] ?>"><img class="articleImg" src="<?=$row['image'] ?>" alt="<?=$row['title'] ?>"/></a>
                            <? } ?>
                            <p>
                                <? /*if($row['image']) { ?>
                                    <img src="<?=$row['image'] ?>">
                                <? }*/ ?>
                                <?=$row['notice'] ?>
                            </p>
                            <p class="news-item-date"><?=$row['date'] ?></p>
                        </div>
                        <? } ?>
                    </div>
                <? } ?>

                <? if(isset($_photo)) { ?>
                    <div class="article-block-header">
                        <div class="title">Фоторепортажи</div>
                        <div class="more"><a href="<?=$photoUrl ?>">все фоторепортажи »</a></div>

                    </div>
                    <div class="clearFloat"></div>
                    <div class="article-block  phote-block">
                        <? foreach($_photo as $row) { ?>
                        <div class="news-item">
                            <div class="news-header"><h3><a href="<?=$row['url'] ?>"><?=$row['header'] ?></a></h3></div>
                            <? if($row['image']) { ?>
                            <div class="news-img">
                                <a href="<?=$row['url'] ?>"><img class="articleImg" src="<?=$row['image'] ?>" alt="<?=$row['title'] ?>"/></a>
                            </div>
                            <? } ?>
                        </div>
                        <? } ?>
                    </div>
                <? } ?>

            </div>

        <div class="footer-part">
            <div class="sep-top"></div>
            <div class="main-content">
                <div class="border-solid"></div>
                <div class="alfa-links">
                    <? foreach($_brand as $t=>$page) { ?>
                    <div class="alfa-block">
                        <div class="alfa-letter"><?=$t ?></div>
                        <div class="alfa-links-for-letter">
                        <? $i = 0; foreach($page as $list) { $i++ ?>
                            <ul>
                            <? foreach($list as $row) { ?>
                                <li><a href="<?=$row['url'] ?>"><?=$row['name'] ?></a><? if($row['isNew']){ ?> <span class="new">NEW</span><? } ?></li>
                            <? } ?>
                            </ul>
                        <? } ?>
                        <? for(;$i<4;$i++) { ?>
                            <ul><li></li></ul>
                        <? } ?>
                        </div>
                    </div>
                    <div class="border-dash"></div>
                    <? } ?>
                </div>
            </div>
            <div class="sep-btm"></div>
        </div>


        <div class="footer-cart colorFon">
            <div class="main-content">
                <div class="alfa-links footer-cart-content">
                    <div class="main-content-cart">
                        <div class="left"><?=$cart['notice'] ?></div>
                        <div class="left image"><?=$cart['payment'] ?></div>
                    </div>
                </div>
            </div>
        </div>


        <div class="footer-text">
            <div class="main-content">
                <p><?=$copyright ?></p>
                <?=$counters ?>
            </div>
        </div>
    </div>
    <div class="milestone"></div>
<div id="idAjaxLog"></div>
</body>
</html>