	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$edit->html()->startForm() ?>
<? list($form) = $edit->current()->main ?>
<table class="great_table">
<tr class="header_col">
<td colspan="2">&nbsp;</td>
</tr>

<tr>
<td class="svet_td">Копирайт:</td>
<td class="svet_td2"><?=$form->html('copyright', 'class="width99" rows="10"') ?></td>
</tr>

</table>
<?=$edit->html()->endForm() ?>


	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>