<table class="great_table sectionCommand">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionCommand').hide(); $('.sectionEdit').show(); ">Показать настройки</a></td>
</tr>
</table>

<?=$config->html()->startForm('edit') ?>
<? list($configForm) = $config->current()->main ?>
<table class="great_table sectionEdit cHide"">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionEdit').hide(); $('.sectionCommand').show(); ">Скрыть настройки</a></td>
</tr>
<tr>
<td colspan="2" class="svet_td">
    <? view_command::viewLineButton(
                       cmfAdminView::buttonType1("edit.postAjax('update');", 'Сохранить')) ?>
</td>
</tr>
<tr>
<td class="svet_td">&nbsp;</td>
<td class="svet_td2 selectCheckbox width200"><?=$configForm->html('isActivate') ?></td>
</tr>
<tr>
<td class="svet_td">Обратная связь:</td>
<td class="svet_td2"><?=$configForm->html('callback', 'class="width99" rows="7"') ?></td>
</tr>
<tr>
<td class="svet_td">Информация на странице заказа:</td>
<td class="svet_td2"><?=$configForm->html('basket', 'class="width99" rows="7"') ?></td>
</tr>
<tr>
<td class="svet_td">Заказов на странице:</td>
<td class="svet_td2"><?=$configForm->html('orderLimit', 'class="width25"') ?></td>
</tr>
<tr>
<td class="svet_td">Количество страниц (навигация):</td>
<td class="svet_td2"><?=$configForm->html('orderPage', 'class="width25"') ?></td>
</tr>
<tr>
<td class="svet_td">Заказов на странице пользователя:</td>
<td class="svet_td2"><?=$configForm->html('mainLimit', 'class="width25"') ?></td>
</tr>
</table>
<?=$config->html()->endForm() ?>



<?=$list->html()->startForm('filter') ?>
	<table class="table_position">
	<tr class="header_col">
	<td width="50%">
	Контактное лицо<br /><input name="name" id="name" type="text" value="<?=$name ?>" class="width50">
	<?=cmfAdminView::onclickType1("filter.postAjax('changeFilter');", 'Найти') ?>&nbsp;&nbsp;
	<?=cmfAdminView::onclickType1("cmf.setValue('name', ''); filter.postAjax('changeFilter');", 'Сброс') ?>
	</td>
	<td width="50%">
		Почта <br /><input name="email" id="email" type="text" value="<?=$email ?>" class="width50">
		<?=cmfAdminView::onclickType1("filter.postAjax('changeFilter');", 'Найти') ?>&nbsp;&nbsp;
		<?=cmfAdminView::onclickType1("cmf.setValue('email', ''); filter.postAjax('changeFilter');", 'Сброс') ?>
	</td>
	</tr>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLimitButton($limitUrl, $linkPage,
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="150px">Логин</td>
	<td>Контактное лицо</td>
	<td width="200px">>Дата/<br />ip-proxy последнего захода</td>
	<td width="150px">Действия</td>
	<td width="22px">Вкл</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($list) ?>

	<td><?=$data->login ?></td>
	<td><? if($key) echo cmfAdminView::buttonType3($list->getEditUrl(), $data->name) ?></td>
	<td><?=$data->sesDate ?><br><?=$data->sesIp ?>(<?=$data->sesProxy ?>)</td>

	<td>
		<? 	$userUnban = !$data->is('ban') ? 'cHide' : '';
			$userExit = $data->is('ban') ? 'cHide' : '';
		?>
		<div id="userUnban<?=$key ?>" class="<?=$userUnban ?>">
		<?=cmfAdminView::onclickType1("modul.ajax('userUnban', '$key');", 'Разбан') ?>
		</div>
		<div id="userExit<?=$key ?>" class="<?=$userExit ?>">
		<?=cmfAdminView::onclickType1("modul.ajax('userExit', '$key');", 'Выход') ?>
		</div>
	</td>

	<td>
        <? if($data->register==='no') { ?>
            <?=cmfAdminView::onclickType1("modul.postAjax('activate', '$key');", 'Активировать') ?>
        <? } else { ?>
            <?=$form->html('visible') ?>
        <? } ?>
	</td>
    <td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLimitButton($limitUrl, $linkPage,
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
