<table class="great_table sectionCommand">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionCommand').hide(); $('.sectionEdit').show(); ">Показать настройки</a></td>
</tr>
</table>

<?=$config->html()->startForm('edit') ?>
<? list($configForm) = $config->current()->main ?>
<table class="great_table sectionEdit cHide"">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionEdit').hide(); $('.sectionCommand').show(); ">Скрыть настройки</a></td>
</tr>
<tr>
<td colspan="2" class="svet_td">
    <? view_command::viewLineButton(
                       cmfAdminView::buttonType1("edit.postAjax('update');", 'Сохранить')) ?>
</td>
<tr>
<td class="svet_td">&nbsp;</td>
<td class="svet_td2 selectCheckbox">
    <?=$configForm->label('isAnimation', 'Анимация на главной') ?>
</td>
</tr>
<tr>
<td class="svet_td">Паузы между анимацией</td>
<td class="svet_td2 selectCheckbox"><?=$configForm->html('animationTime', 'class="width25"') ?></td>
</tr>
<tr>
<td class="svet_td">Логотип:</td>
<td class="svet_td2"><?=$config->getImage('main', 'logo') ?></td>
</tr>
<tr>
<td class="svet_td">Время работы:</td>
<td class="svet_td2"><?=$configForm->html('time', 'class="width50"') ?></td>
</tr>
<tr>
<td class="svet_td">Телефон:</td>
<td class="svet_td2"><?=$configForm->html('phone', 'class="width50"') ?></td>
</tr>
<tr>
<td class="svet_td">Число товаров<br />в Новинки / Популярные:</td>
<td class="svet_td2"><?=$configForm->html('productLimit', 'class="width50"') ?></td>
</tr>
<tr>
<td class="svet_td">Email:</td>
<td class="svet_td2"><?=$configForm->html('email', 'class="width50"') ?></td>
</tr>
<tr>
<td class="svet_td">Соц сети:</td>
<td class="svet_td2"><?=$configForm->html('network', 'class="width99" rows="10"') ?></td>
</tr>

<tr class="header_col">
<td colspan="2">Позвоните мне</td>
</tr>
<tr>
<td class="svet_td">&nbsp;</td>
<td class="svet_td2 selectCheckbox">
    <?=$configForm->label('callBackOn', 'Модуль включён') ?>
    <span class="callBackTemplateSms"><?=$configForm->label('callBackIsEmail', 'Дублировать сообщение на почту', 'onchange="cmf.pages.callBackTypeShange();"') ?></span>
</td>
</tr>
<tr>
<td class="svet_td">Тип уведомления:</td>
<td class="svet_td2"><?=$configForm->html('callBackType', 'class="width50" onchange="cmf.pages.callBackTypeShange();"') ?>
<script language="JavaScript">
cmf.pages.callBackTypeShange = function(v) {
    if(cmf.getValue('<?=$configForm->getId('callBackType') ?>')=='email') {
    	$('.callBackTemplateEmail').show();
    	$('.callBackTemplateSms').hide();
    } else {
        if(cmf.isChecked('<?=$configForm->getId('callBackIsEmail') ?>')) {
            $('.callBackTemplateEmail').show();
        } else {
            $('.callBackTemplateEmail').hide();
        }
        $('.callBackTemplateSms').show();
    }
}
cmf.pages.callBackTypeShange();
</script>
</td>
</tr>
<tr>
<td class="svet_td">Шаблон:</td>
<td class="svet_td2">
    <div class="callBackTemplateSms">
        Получатель:<br>
        <?=$configForm->html('callBackSms', 'class="width25"') ?>
        <div class="clearFloat"></div>
        <textarea readonly="true" rows="4" class="width50">
        Тема:   {title}
        Имя:    {name}
        Контактный телефон: {phone}
        Интернет магазин:   {proectName}
        </textarea>
        <div class="clearFloat"></div>
        <?=$configForm->html('callBackTemplateSms', 'class="width50" rows="4"') ?>
        <div class="clearFloat"></div>

        <br>Лимит sms в час:
        <div class="clearFloat"></div>
        <?=$configForm->html('callBackSmsLimit', 'class="width25"') ?>
        <br><br>
    </div>
    <?=$configForm->html('callBackTemplateEmail', 'class="callBackTemplateEmail width50"') ?>
    <div class="clearFloat"></div>
</td>
</tr>
<tr>
<td class="svet_td">Сообщение над формой:</td>
<td class="svet_td2"><?=$configForm->html('callBackNotice', 200) ?></td>
</tr>

</table>
<?=$config->html()->endForm() ?>

	<? view_command::viewLimitButton($list->getLimitUrl(), $list->getLinkPage(),
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td>Название</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($list) ?>
	<?=$list->getPostMove($data) ?>
	<td><? if($key) echo cmfAdminView::buttonType3($list->getEditUrl(), $data->name) ?></td>
	<td><?=$form->html('visible') ?></td>
	<td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLimitButton($list->getLimitUrl(), $list->getLinkPage(),
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
