	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjaxSave('update');", 'Сохранить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить') .
	                   cmfAdminView::buttonType2($edit->url()->getCatalog(), 'Вернуться')) ?>


<?=$edit->html()->startForm() ?>
<? list($form) = $edit->current()->main ?>
<table class="great_table">

<tr class="header_col">
<td colspan="2">&nbsp;</td>
</tr>

<tr>
<td class="svet_td"></td>
<td class="svet_td2 selectCheckbox">
<? if($data->register==='no') { ?>
     <?=cmfAdminView::onclickType1("modul.postAjax('activate');", 'Активировать') ?>
<? } else { ?>
    <?=$form->label('visible', 'Включить') ?>
    <?=$form->label('isIp', 'Привязывать сессию к ip') ?>
<? } ?>
</td>
</tr>

<tr>
<td class="svet_td" id="userName">Имя: *</td>
<td class="svet_td2"><?=$form->html('name', 'class="width50"') ?></td>
</tr>

<tr>
<td class="svet_td" id="userName">Фамилия: *</td>
<td class="svet_td2"><?=$form->html('family', 'class="width50"') ?></td>
</tr>

<tr>
<td class="svet_td">Логин: *</td>
<td class="svet_td2"><?=$form->html('login', 'class="width50"') ?></td>
</tr>

<tr>
<td class="svet_td">Пароль:</td>
<td class="svet_td2"><?=$form->html('password', 'class="width50"') ?></td>
</tr>

<tr>
<td class="svet_td">Подтвердите пароль:</td>
<td class="svet_td2"><?=$form->html('password2', 'class="width50"') ?></td>
</tr>

</table>
<?=$edit->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjaxSave('update');", 'Сохранить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить') .
	                   cmfAdminView::buttonType2($edit->url()->getCatalog(), 'Вернуться')) ?>