	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td>Название</td>
<!--//	<td width="100px">Копировать</td>//-->
	<td width="100px">Фильтры</td>
	<td width="100px">Описание</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($list) ?>
	<td><? if($key) echo cmfAdminView::buttonType3($list->getEditUrl(), $data->name) ?></td>
<!--//	<td><?=cmfAdminView::onclickType1("modul.post('copy', $key)", 'копировать') ?></td>//-->
	<td><?=cmfAdminView::buttonType3($list->getSelectUrl(), 'фильтры') ?></td>
	<td><?=cmfAdminView::buttonType3($list->getNoticeUrl(), 'описание') ?></td>
	<td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
