    <div id="main" class="basket bcont">
        <div class="l-block item-info">
            <div class="order-block order-block_view2"><div class="o2"><div class="o3 o3_password">
        	<?=$password->startForm() ?>
                <div class="bcont blockText">
                    <h1>Изменить пароль</h1>
                    <?=$content ?>
                    <?=$password->formError() ?>
                	<?=$password->formSave() ?>
                    <?=$form->viewError('passwordMain') ?>
                    <div class="block"><b>Старый пароль</b><span class="input"><i><?=$form->html('passwordMain') ?></i></span></div>

                    <div class="clearFloat"></div>
                    <?=$form->viewError('password') ?>
                    <div class="block"><b>Пароль</b><span class="input"><i><?=$form->html('password') ?></i></span></div>

                    <div class="clearFloat"></div>
                    <?=$form->viewError('password2') ?>
                    <div class="block"><b>Подтверждение пароля</b><span class="input"><i><?=$form->html('password2') ?></i></span></div>
                </div>
                <div class="clearFloat"></div>
                <input type="image" src="images/save-type2.png" class="reg-btn"   />
            <script type="text/javascript">
            cmf.getId('<?=$form->getId('passwordMain') ?>').errorView = cmf.main.form.login;
            cmf.getId('<?=$form->getId('password') ?>').errorView = cmf.main.form.login;
            cmf.getId('<?=$form->getId('password2') ?>').errorView = cmf.main.form.login;
            </script>
            <?=$password->endForm() ?>
            </div></div></div>
        </div>
    </div>