    <div id="main" class="basket bcont">
        <div class="l-block item-info">
            <div class="order-block order-block_view2"><div class="o2"><div class="o3 o3_password">
            <?=$userRegister->startForm() ?>
                <div class="bcont blockText">
                    <h1>Личные данные</h1>
                    <?=$content ?>
                    <?=$userRegister->formError() ?>
                    <?=$userRegister->formSave() ?>
                    <?=$form->viewError('name') ?>
                    <div class="block"><b>Имя</b><span class="input"><i><?=$form->html('name') ?></i></span></div>

                    <div class="clearFloat"></div>
                    <?=$form->viewError('family') ?>
                    <div class="block"><b>Фамилия</b><span class="input"><i><?=$form->html('family') ?></i></span></div>

                    <div class="clearFloat"></div>
                    <?=$form->viewError('login') ?>
                    <div class="block"><b>Email</b><span class="input"><i><?=$form->html('login') ?></i></span></div>

                    <div class="clearFloat"></div>
                    <?=$formAll->viewError('cod') ?> <?=$formAll->viewError('phone') ?>
                    <div class="block i-small"><b>Телефон</b>
                        <span class="input"><i><?=$formAll->html('cod', 'data-default="8(___)"') ?></i></span>
                        <span class="input input2"><i><?=$formAll->html('phone') ?></i></span>
                    </div>
                    
                    <div class="clearFloat"></div>
                    <?=$formAll->viewError('gorod') ?>
                    <div class="block"><b>Город</b><span class="input"><i><?=$formAll->html('gorod') ?></i></span></div>

                    <div class="clearFloat"></div>
                    <?=$formAll->viewError('index') ?>
                    <div class="block"><b>Индекс</b><span class="input"><i><?=$formAll->html('index') ?></i></span></div>

                </div>
                <div class="clearFloat"></div>
                <input type="image" src="images/save-type2.png" class="reg-btn"   />
            <script type="text/javascript">
            $(function($){
                $("#<?=$formAll->getId('cod') ?>").mask("+7(999)");
                $("#<?=$formAll->getId('phone') ?>").mask("999-99-99");
            });                
                
            cmf.getId('<?=$form->getId('name') ?>').errorView = cmf.main.form.login;
            cmf.getId('<?=$form->getId('family') ?>').errorView = cmf.main.form.login;
            cmf.getId('<?=$form->getId('login') ?>').errorView = cmf.main.form.login;

            cmf.getId('<?=$formAll->getId('cod') ?>').errorView = cmf.main.form.login;
            cmf.getId('<?=$formAll->getId('phone') ?>').errorView = cmf.main.form.login;
            </script>
            <?=$userRegister->endForm() ?>
            </div></div></div>
        </div>
    </div>