
    <h1>Восстановление пароля</h1>
    <?=$content ?>
    <div class="register-page">
    <?=$password->startForm() ?>
    <?=$password->formError() ?>
            <fieldset>
                <label>Email</label>
                <?=$form->html('login', 'class="i-text"') ?>
            </fieldset>
            <fieldset>
                <label>Код безопасности</label>
                <?=$form->html('captcha', 'class="i-text noreq"') ?>
            </fieldset>
            <fieldset>
                <label><a onclick="<?=$form->get('captcha')->jsReloadImage() ?>">Обновить код</a></label>
                <?=$password->form()->get()->get('captcha')->image() ?>
            </fieldset>
            <fieldset>
                <input type="image" src="images/send.png" class="reg-btn"   />
            </fieldset>

    <script type="text/javascript">
    cmf.getId('<?=$form->getId('login') ?>').errorView = cmf.main.form.login;
    cmf.getId('<?=$form->getId('captcha') ?>').errorView = cmf.main.form.login;
    </script>
    <?=$password->endForm() ?>
    </div>
