	<table class="table_position">
	<tr class="header_col">
	<td>Раздел: <?=cmfView::selectOncahge($filterSection) ?></td>
	</tr>
	</table>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td>Название</td>
	<td width="300px">Описание</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($list as $key=>$value){
		list($form, $data) = $value->main;
	 ?>
	<?=view_list::startTR($list) ?>

	<td><?=cmfAdminView::buttonType3($list->getEditUrl(), $data->name) ?></td>
	<td><?=$data->notice ?></td>
	<td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
