<?
view_command::viewLineButton(
        cmfAdminView::buttonType1("modul.postAjaxSave('update');", 'Сохранить') .
        cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить') .
        cmfAdminView::buttonType2($edit->url()->getCatalog(), 'Вернуться'))
?>



<?= $edit->html()->startForm() ?>
<? list($form) = $edit->current()->main ?>
<table class="great_table">
    <tr class="header_col">
        <td colspan="2">&nbsp;</td>
    </tr>

    <tr>
        <td class="svet_td">&nbsp;</td>
        <td class="svet_td2 selectCheckbox">
            <?= $form->label('visible', 'Отображать') ?></td>
    </tr>

    <tr>
        <td class="svet_td">Тип:</td>
        <td class="svet_td2"><?= $form->html('type', 'class="width50"') ?></td>
    </tr>

    <tr>
        <td class="svet_td">Адрес:</td>
        <td class="svet_td2">
            В адресе можно указывать {*} - заменяет любую последовательность символов
            <br />Пример /ghenskaja_odeghda_i_akse/{*}
            <br /><?= $form->html('adress', 'class="width50"') ?></td>
    </tr>

    <tr>
        <td class="svet_td">Название:<?= cmfWysiwyng::typograf($form->getId('name')) ?></td>
        <td class="svet_td2"><?= $form->html('name', 'class="width99"') ?></td>
    </tr>

    <tr>
        <td class="svet_td">Описание:</td>
        <td class="svet_td2"><?= $form->html('content', 400) ?></td>
    </tr>

</table>
<?= $edit->html()->endForm() ?>

<?
view_command::viewLineButton(
        cmfAdminView::buttonType1("modul.postAjaxSave('update');", 'Сохранить') .
        cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить') .
        cmfAdminView::buttonType2($edit->url()->getCatalog(), 'Вернуться'))
?>