<table class="great_table">
<tr class="header_col">
<td colspan="2">Настройки для прайса <?=view_siteUrl::viewSiteUrl(cmfCronSiteMap::getUrlFile()) ?></td>
</tr>
</table>


<table class="great_table sectionCommand">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionCommand').hide(); $('.sectionEdit').show(); ">Показать настройки</a></td>
</tr>
</table>

<?=$config->html()->startForm('edit') ?>
<? list($configForm) = $config->current()->main ?>
<table class="great_table sectionEdit cHide"">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionEdit').hide(); $('.sectionCommand').show(); ">Скрыть настройки</a></td>
</tr>
<tr>
<td colspan="2" class="svet_td">
    <? view_command::viewLineButton(
                       cmfAdminView::buttonType1("edit.postAjax('update');", 'Сохранить')) ?>
</td>
</tr>
</table>
<?=$config->html()->endForm() ?>




	<? view_command::viewLineMenuButton(
	                   cmfAdminView::buttonType1("modul.postAjax('updateSitemap');", 'Сгенерировать файл'),
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить').
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table width="1000px" class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td>Модуль</td>
	<td width="150px">Вероятная частота изменения</td>
	<td width="100px">Приоритетность</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	$i = false;
	foreach($list as $key=>$value){
		list($form, $data) = $value->main;

	 ?>
	<?=view_list::startTR($list) ?>
	<?=$list->getPostMove($data); ?>

	<td><?=$form->html('name', 'class="width50"') ?></td>
	<td><?=$form->html('changefreq', 'class="width99"') ?></td>
	<td><?=$form->html('priority', 'class="width50"') ?></td>
	<td><?=$form->html('visible') ?></td>
    <td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить').
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>