<!DOCTYPE html>
<html>
    <head>
        <title><?= $title ?></title>
        <meta http-equiv="pragma" content="no-cache" />
        <meta http-equiv="cache-control" content="no-cache" />
        <?= cmfHeader::getHead() ?>
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>
        <noscript>
        <strong>Системе обязательна поддержка javascript, включите ee и обновите страницу</strong>
        </noscript>
        <script language="JavaScript">
            core.ajax.init({hash: '<?= $this->hash() ?>'});
        </script>
        <div id="ajax-content">