
    <h1 class="item-block">Заказ № <?=$orderId ?> (<?=$status ?>) <?=$date ?></h1>
    <div class="clearFloat"></div>

                <div id="main" class="basket bcont">
                        <div class="l-block item-info l-block-order item-info-order">

                            <div class="t-title t-title-order">
                                <span class="nr1 nr1-order">наименование</span>
                                <span class="nr2">количество</span>
                                <span class="nr3 border-none">стоимость</span>
                            </div>
<?
$index = 1;
foreach($_basket as $k=>$v) {
    $is = true;
    foreach($v['param'] as $pId=>$pName) if(isset($v['count'][$pId])) {
        foreach($v['count'][$pId] as $cId=>$cValue) if(isset($v['color'][$cId]) or !$cId) { ?>
                            <div class="item item-order <?=$is ? 'itemFirst' : 'itemNext' ?>">
                                <span class="nr1 nr1-order">
                                    <? if($is) { ?>
                                        <div class="img"><img src="<?=$v['image'] ?>" alt="<?=$v['title'] ?>" width="45" /></div>
                                        <h6><a href="<?=$v['url'] ?>"><?=$v['name'] ?></a>
                                            <sup id="comment<?=$k ?>_<?=$pId ?>_<?=$cId ?>"><? if(!empty($v['comment'][$pId][$cId])) { ?>(<?=$v['comment'][$pId][$cId] ?>)<? } ?></sup>
                                        </h6>
                                    <? } else { ?>
                                        <div class="imgNone"></div>
                                        <sup id="comment<?=$k ?>_<?=$pId ?>_<?=$cId ?>"><? if(!empty($v['comment'][$pId][$cId])) { ?>(<?=$v['comment'][$pId][$cId] ?>)<? } ?></sup>
                                    <? } ?>
                                    <div class="text">
                                        <? if($is) { ?>
                                            <?=$v['bName'] ?><br />
                                        <? } ?>
                                        <? if($pId) { ?>
                                            <?=$v['header'] ?> <?=$pName ?><? if($cId) { echo ';';} ?>
                                        <? } ?>
                                        <? if($cId) { ?>
                                            Цвет: <?=$v['color'][$cId]['name'] ?>
                                        <? } ?>
                                    </div>
                                </span>
                                <span class="nr2">
                                    <b><?=$cValue ?></b>
                                </span>
                                <span class="nr3 border-none"><?=$v['view'][$pId][$cId] ?><b></b></span>
                            </div>
<?  $is = false;
    } }
} ?>


                          </div>
                          <div class="r-block item-right item-right-order item-right-basket-order">

                              <div class="order-block-data"><div class="o2"><div class="o3 o3_order">
                                <div class="bcont confidentialData">
                                <? if(isset($isView)) { ?>
                                    <div class="tittle tittle-top">Конфиденциальные данные</div>
                                    <div class="clearFloat"></div>
                                    <?=$content ?>
                                    <div class="clearFloat"></div>

                                    <div class="user-order-view">
                                    <?=$orderView->startForm() ?>
                                	<?=$orderView->formError() ?>
                                        <?=$form->viewError('email') ?>
                                        <div class="clearFloat"></div>
                                        <fieldset>
                                            <label>Email</label>
                                            <?=$form->html('email', 'class="i-text i-text-middle"') ?>
                                        </fieldset>
                                        <br />
                                        <fieldset>
                                            <input type="image" src="images/send-fancybox.png" class="reg-btn"   />
                                        </fieldset>
                                    <script type="text/javascript">
                                    cmf.getId('<?=$form->getId('email') ?>').errorView = cmf.main.form.login;
                                    </script>
                                	<?=$orderView->endForm() ?>
                                    </div>

                                <? } else { ?>
                                    <div class="tittle tittle-top">Данные заказа</div>
                                    <? foreach($userData as $k=>$v) { ?>
                                        <b><?=$k ?>: <i><?=is_null($v) ? '' : ''. $v ?></i></b>
                                    <? } ?>
                                    <div class="tittle">Доставка</div>
                                    <? foreach($userAdress as $k=>$v) { ?>
                                        <b><?=$k ?>: <i><?=is_null($v) ? '' : ''. nl2br($v) ?></i></b>
                                    <? } ?>
                                    <? if(isset($EMS)) { ?>
                                        <b>Номер отправления EMS: <i><?=$EMS ?></i></b>
                                    <? } ?>
                                    <? if($userSubscribe) { ?>
                                    <div class="tittle">Подписка на новости</div>
                                    <? foreach($userSubscribe as $k=>$v) { ?>
                                        <b><?=$k ?><?=is_null($v) ? '' : ' '. $v ?></b>
                                    <? }} ?>


                                    <? if(isset($deliveryDesc)) { ?>
                                        <div class="tittle tittle-top">
                                            <br><a id="contentDeliveryLink" href="#contentDelivery">Статус доставки</a>
                                        </div>
                                        <div class="cHide"><div id="contentDelivery" class="item-block">
                                            <h1>Статус доставки</h1>
                                            <?=$deliveryDesc['content'] ?>
                                        </div></div>
                                        <script type="text/javascript">
                                            $("#contentDeliveryLink").fancybox({ });
                                            function Wind(ID) {
                                                var link = "http://www.russianpost.ru/resp_engine.aspx?Path=RP/SERVISE/RU/Home/postuslug/SearchOPS/SearchOPSPortalExtended&NEWSID=" + ID;
                                                window.open(link, "", "menubar=no,scrollbars=1,resizable=no,width=750, height=500");
                                            }
                                        </script>
                                    <? } ?>

                                <? } ?>
                                </div>
                              </div></div></div>

                              <div class="r-block-order2">
                                  <div id="basketPrice">
                                        <b>Всего товаров на сумму</b>
                                        <b class="price"><i><?=$priceAll ?></i></b>
                                        <? if($discount) { ?>
                                            <b>Цена со скидкой</b>
                                            <b class="price"><i><?=$priceDiscount ?></i></b>
                                        <? } ?>
                                        <? if(isset($priceDelivery)) { ?>
                                            <b>Цена с доставкой</b>
                                            <b class="price"><i><?=$priceDelivery ?></i></b>
                                        <? } ?>
                                        <? if($discount) { ?>
                                            <b>Скидка</b>
                                            <b class="price"><i><?=$discount ?></i></b>
                                        <? } ?>
                                  </div>
                              </div>
                          </div>
                </div>