<table class="great_table sectionCommand">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionCommand').hide(); $('.sectionEdit').show(); ">Показать настройки</a></td>
</tr>
</table>

<?=$config->html()->startForm('edit') ?>
<? list($configForm) = $config->current()->main ?>
<table class="great_table sectionEdit cHide"">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionEdit').hide(); $('.sectionCommand').show(); ">Скрыть настройки</a></td>
</tr>
<tr>
<td colspan="2" class="svet_td">
    <? view_command::viewLineButton(
                       cmfAdminView::buttonType1("edit.postAjax('update');", 'Сохранить')) ?>
</td>
</tr>
<tr>
<td class="svet_td"> </td>
<td class="svet_td2"><?=$configForm->label('visible', 'Сервис включен') ?></td>
</tr>
<tr>
<td class="svet_td">Лимит sms в час:</td>
<td class="svet_td2"><?=$configForm->html('smsLimit', 'class="width25"') ?></td>
</tr>
<tr>
<td class="svet_td">Api:</td>
<td class="svet_td2"><?=$configForm->html('api', 'class="width50"') ?></td>
</tr>
<tr>
<td class="svet_td">Логин:</td>
<td class="svet_td2"><?=$configForm->html('login', 'class="width50"') ?></td>
</tr>
<tr>
<td class="svet_td">Пароль:</td>
<td class="svet_td2"><?=$configForm->html('password', 'class="width50"') ?></td>
</tr>
<tr>
<td class="svet_td">Подверждение пароля:</td>
<td class="svet_td2"><?=$configForm->html('password2', 'class="width50"') ?></td>
</tr>
<tr>
<td class="svet_td">Подпись отправителя:</td>
<td class="svet_td2"><?=$configForm->html('sender', 'class="width50"') ?></td>
</tr>

</table>
<?=$config->html()->endForm() ?>

<table class="great_table">
<tr class="columnn_svet2">
<td colspan="2">В сообщениях можно использовать:
<br>{№} - Номер заказа
<br>{orderUrl} - Адрес заказа
<br>{name} - ФИО пользователя
</td>
</tr>
</table>


	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td width="150px">Статус</td>
	<td>Текст</td>
	<td width="22px">Вид</td>
	<td width="22px">Удалить</td>
	</tr>

<?	foreach($list as $key=>$value){
		list($form, $data) = $value->main;
	 ?>
	<?=view_list::startTR($list) ?>
	<?=$list->getPostMove($data) ?>
	<td><?=$form->html('status', 'class="width99"') ?></td>
	<td><?=$form->html('notice', 'class="width99" rows="3"') ?></td>
	<td><?=$form->html('visible') ?></td>
	<td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
