    <table class="great_table">
    <tr class="header_col">
    <td><?=cmfView::selectOncahge($filterView, 'class="width99"') ?></td>
    </tr>
    </table>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="22px">#</td>
	<td colspan="<?=$list->getColspan() ?>">Название</td>
	<td width="220px">Постоянная ссылка</td>
	<td width="100px">Добавить подраздел</td>
	<td width="22px">Вид</td>
	<td width="22px">Уд.</td>
	</tr>

<?	foreach($list as $key=>$value){
		list($form, $data) = $value->main;
	 ?>
	<?=view_list::startTR($list) ?>

	<? view_list_tree::viewTreeLine($key, $data) ?>

	<?=$list->getPostMove($data) ?>
	<td <?=$list->getColspanLine($data) ?>>
		<?=cmfAdminView::buttonType3($list->getEditUrl(), $data->name) ?>
	</td>

	<td><?=$list->viewListSiteUrl($data) ?></td>
	<td><?= $data->level<1 ? cmfAdminView::buttonType3($list->getAddChildUrl(), 'Добавить') : '' ?> </td>
	<td><?=$form->html('visible') ?></td>
	<td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType2($list->url->getNew(), 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>
