    <? view_command::viewLineMenuButton(
                       cmfAdminView::buttonType1("modul.postAjax('updateDump');", 'Обновить размеры')) ?>

<table class="great_table sectionCommand">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionCommand').hide(); $('.sectionEdit').show(); ">Показать настройки</a></td>
</tr>
</table>

<?=$config->html()->startForm('edit') ?>
<? list($configForm) = $config->current()->main ?>
<table class="great_table sectionEdit cHide"">
<tr class="header_col">
<td colspan="2"><a onclick="$('.sectionEdit').hide(); $('.sectionCommand').show(); ">Скрыть настройки</a></td>
</tr>
<tr>
<td colspan="2" class="svet_td">
    <? view_command::viewLineButton(
                       cmfAdminView::buttonType1("edit.postAjax('update');", 'Сохранить')) ?>
</td>
</tr>
<tr>
<td class="svet_td">&nbsp;</td>
<td class="svet_td2"><?=$configForm->label('run', 'Синхранихация размеров включена') ?></td>
</tr>
</table>
<?=$config->html()->endForm() ?>


	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<?=$list->html()->startForm() ?>
	<table class="great_table">
	<tr class="header_col">
	<td>Значение на стороннем сайте</td>
	<td width="200px">Параметр</td>
	<td width="200px">Значение</td>
	<td width="22px">Удалить</td>
	</tr>

<?	foreach($list as $key=>$value){
		list($form, $data) = $value->main;
	 ?>
	<?=view_list::startTR($list) ?>
	<td><?=$form->html('name', 'class="width99"') ?></td>
	<td><?=$form->html('param', 'class="width99" onchange="modul.postAjax(\'onchangeParam\', '. $key .' ? '. $key .' : this.keyIndex);"') ?></td>
	<td><?=$form->html('value', 'class="width99"') ?></td>
	<td><?=$list->viewDelete() ?></td>
	</tr>
<? } ?>
	</table>
<?=$list->html()->endForm() ?>

	<? view_command::viewLineButton(
	                   cmfAdminView::buttonType1("modul.postAjax('newLine');", 'Добавить') .
	                   cmfAdminView::buttonType1("modul.postAjax('update');", 'Применить')) ?>


<? if($log) { ?>
	<table class="great_table">
	<tr class="header_col">
	<td width="150px">Дата</td>
	<td>Результат</td>
	</tr>
<?	foreach($log as $row) {
        $color = isset($row['isNew']) ? ' class="red"' : '';?>
    	<tr <?=view_list::styleTR() ?>>
    	<td <?=$color ?>><?=$row['date'] ?></td>
    	<td <?=$color ?>><?=$row['content'] ?></td>
    	</tr>
<? } ?>
	</table>
<? } ?>